// app/sitemap.ts — the pages this app wants indexed
//
// 2026-08-16: this app had no sitemap, so discovery depended on a crawler
// finding an internal link. Generated rather than static, so it cannot drift
// out of date as pages are added.
import type { MetadataRoute } from 'next'

const BASE = 'https://javarispirits.com'

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return [
    { url: `${BASE}`, lastModified: now, changeFrequency: 'weekly', priority: 1 },
    { url: `${BASE}/academy`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/admin/process-images`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/advertise`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/auth/login`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/auth/register`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/barrel-aging`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/barrels`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/blog`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/business/dashboard`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/business/pricing`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/business/register`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/challenges`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/cocktails`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/cocktails/genius`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/collection`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/collections`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/community`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/courses`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/dashboard`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/digital-cards`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/distilleries`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/docs`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/events`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/explore`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/find`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/flavors`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/games`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/games/trivia`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/help`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/history`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/javari`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/journal`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/labels`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/leaderboard`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/learn`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/login`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/maker`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/maker/dashboard`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/marketplace`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/museum`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/mysite`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/offline`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/party-games`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/prices`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/pricing`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/profile`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/programs`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/referral`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/retailers`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/rewards`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/scan`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/scanner`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/share`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/signup`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/spirits`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/stores`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/submit`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/subscription`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/subscription/success`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/tasting`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/tasting-notes`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/today`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/tour`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/tours`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/value`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/whales`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/where-to-buy`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/wrapped`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
  ]
}
