// app/api/support/auto-ticket/route.ts
// Auto-generates support tickets from client-side errors

import { NextRequest, NextResponse } from 'next/server';
import { lazyAdminDb } from '@/lib/supabase/admin';
const supabase = lazyAdminDb();

interface ErrorTicketPayload {
  error_message: string;
  error_stack?: string;
  component_name?: string;
  url: string;
  user_agent: string;
  user_id?: string;
  user_email?: string;
  additional_context?: Record<string, unknown>;
}

export async function POST(request: NextRequest) {
  try {
    const payload: ErrorTicketPayload = await request.json();

    // Determine priority based on error type
    let priority = 'medium';
    let category = 'bug';
    
    if (payload.error_message.includes('ChunkLoadError') || 
        payload.error_message.includes('Loading chunk')) {
      priority = 'low';
      category = 'technical';
    } else if (payload.error_message.includes('TypeError') || 
               payload.error_message.includes('ReferenceError')) {
      priority = 'high';
    } else if (payload.error_message.includes('NetworkError') || 
               payload.error_message.includes('fetch')) {
      priority = 'medium';
      category = 'technical';
    } else if (payload.error_message.includes('payment') || 
               payload.error_message.includes('stripe') ||
               payload.error_message.includes('subscription')) {
      priority = 'critical';
      category = 'billing';
    }

    // Create the support ticket
    const { data: ticket, error } = await supabase
      .from('bv_support_tickets')
      .insert({
        user_id: payload.user_id || null,
        email: payload.user_email || null,
        subject: `[Auto] ${payload.error_message.substring(0, 100)}`,
        description: `
## Automatic Error Report

**Error Message:**
\`\`\`
${payload.error_message}
\`\`\`

**Component:** ${payload.component_name || 'Unknown'}

**URL:** ${payload.url}

**User Agent:** ${payload.user_agent}

${payload.error_stack ? `**Stack Trace:**\n\`\`\`\n${payload.error_stack.substring(0, 2000)}\n\`\`\`` : ''}

${payload.additional_context ? `**Additional Context:**\n\`\`\`json\n${JSON.stringify(payload.additional_context, null, 2)}\n\`\`\`` : ''}

---
*This ticket was automatically generated by the BarrelVerse error tracking system.*
        `.trim(),
        category,
        priority,
        status: 'open',
        source: 'auto_error',
        error_context: {
          error_message: payload.error_message,
          error_stack: payload.error_stack,
          component_name: payload.component_name,
          url: payload.url,
          user_agent: payload.user_agent,
          timestamp: new Date().toISOString(),
          ...payload.additional_context
        }
      })
      .select('id')
      .single();

    if (error) {
      console.error('Failed to create auto-ticket:', error);
      return NextResponse.json(
        { success: false, error: 'Failed to create ticket' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      ticket_id: ticket.id,
      message: 'Error report submitted successfully'
    });

  } catch (error) {
    console.error('Auto-ticket API error:', error);
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    );
  }
}
